---  
# Variables used by the playbook and are not part
# of the backup-and-restore role
#
# set this to true if director deployed Ceph
is_director_deployed_ceph: false

# stackrc file to source
stack_rc_file_location: /home/stack/stackrc

# stack name for the openstack deployment. defaults to stack
overcloud_stack_name: voltron

# overcloud ansible inventory output file 
tripleo_inventory_file_name: overcloud_inventory.yml

# rear backup server ansible inventory name
rear_backup_server_inventory_file_name: rear_backup_server_inventory.yml

# fqdn of backup server
rear_backup_server_fqdn: backup.voltron.xyz

# rpm packages to preload in the backup server
rear_required_packages:
  - iptables 


# Variables associated with the backup-and-restore role 
# Complete list of role variables are in  /usr/share/ansible/roles/backup-and-restore/defaults/main.yml
tripleo_backup_and_restore_nfs_server: 172.25.48.8
tripleo_backup_and_restore_nfs_storage_folder: /ctl_plane_backups
tripleo_backup_and_restore_nfs_clients_nets: 
  - 172.25.48.0/23
  - 172.25.50.0/24
