# This playbook runs the rear backup on the 
# the OpenStack controllers and copies the image to  the ReaR NFS backup server configured
# in earlier steps. Playbook must be executed includding the TripleO 
# generated inventory file and the 'bar_create_recover_image_tag' ansible tag. 
# Example execution command:
# ansible-playbook -i overcloud_inventory.yml playbooks/05_backup_overcloud.yml --tags bar_create_recover_image
---
- hosts: Controller
  become: true
  name: Creating the recovery images for the Overcloud Controllers
  roles:
  - role: backup-and-restore
